---
- name: Run ls on 192.168.0.248
  hosts: 192.168.0.248
  become: false
  tasks:
    - name: List files in the home directory
      command: ls -l /home/monitorapp
      register: ls_output # ls 명령의 결과를 ls_output 변수에 저장

    - name: Show ls output
      debug:
        var: ls_output.stdout # ls 명령의 표준 출력을 표시
